// <auto-generated />
namespace LibraryApplication.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_member_auth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_member_auth));
        
        string IMigrationMetadata.Id
        {
            get { return "202106020003123_mig_member_auth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
